name: Run Linux Commands

on: [push]

jobs:
  linux-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run basic Linux commands
        run: |
          echo "Running on Linux"
          pwd
          ls -l
          whoami
          uname -a
          df -h
          free -m
